#!/usr/bin/env perl
use strict;
my $python = "python3.11";
# Requirements: wheel and twine
die(usage()) unless ($ENV{TOKEN_pip});
my @repo_extra = (" --verbose ");
# We use this as a simple bool, to dictate whether we use the
# pypi test url, or we are publishing live
my $test = shift // "NULL";
my $base;
if ($test =~ m/test/i) {
	print("Publishing to test environment\n");
	push(@repo_extra, "--repository-url", "https://test.pypi.org/legacy/");
	$base = "test.v5";
} elsif ($test =~ m/prod/i) {
	print("Publishing to prod environment\n");
	$base="v5"; # This is the base version, version5 in this case
} else {
	print("Usage: $0 test|prod\n");
	exit(1);
}

# Add the test repo url if we are in test mode
my @tags = `git tag -l`;
my $version = "$base.0";
foreach (reverse(@tags)) {
	if (m/$base.*/) {
		s/\n//g;
		$version = $_;
		last;
	}
}
my @tmp;
@tmp = split(/$base\./, $version);
$tmp[1] = int($tmp[1]) + 1;

my	$new_version = "$base.$tmp[1]";

print "Last tag is $version. Proposed new tag is $new_version. Proceed? (y/n): ";
my $answer = <STDIN>;
if ($answer =~ '(y|Y)') {
	print("OK, continuing\n");
} else {
	print("Aborting\n");
	exit(1);
}
sleep(1); # give user a moment to panic CTRL-C if needs be
# Write version into file for setup.py
open(FD, ">flac2all_pkg/version");
print FD $new_version;
close(FD);

# Create the git tag
die("Could not create git tag\n") if system("git tag -a '$new_version' -m \"Auto-Release Version $new_version\"");
# And we remove the build and dist folder, to make sure fresh files are used
system("rm -rf ./build ./dist");
# Now run the code to push to pip, you need to "pip install wheel" for bdist_wheel.
die("Could not build\n") if system($python, "./setup.py", "sdist", "bdist_wheel");
die("Could not deploy to pypi\n") if system( join(' ',
	"twine", "upload",
	"-u", "__token__",
	"-p", $ENV{TOKEN_pip},
	@repo_extra,
	glob("dist/*")
));
die();
# Finally, we push the tag to git
die("git push failed\n") if system("git", "push", "origin", $new_version);

print("Complete! To do a test upgrade, run \"pip install -U --index-url https://test.pypi.org/simple/ flac2all\"");


sub usage() {
	die("Usage: $0 (test|prod).\n\tN.B: Please set TOKEN_pip to your PyPi token for upload prior to running.\n");
}
